working_dir = 'D:\\model\\current'
percent = 1
exceptions = None
top = 5

datareal_set = ['ALPHA_067',
                'MA180_HR',
                'MACD_TR',
                'DIF',
                'AD_C',
                'MACD',
                'PB_30PCT',
                'ALPHA_089',
                'MA60',
                'PB_30UP',
                'SHORT60',
                'TERNS',
                'CROSS_SC',
                'LONG180_HR',
                'AVG60',
                'ADDI_C',
                'DEA',
                'ALPHA_169',
                'ADX',
                'RSI1']

data_set = ['RSI2',
            'MACD_TR',
            'MA120_HR',
            'DIF',
            'MA60',
            'TERNS',
            'AD_C',
            'MACD',
            'BIAS3',
            'RSI1',
            'LONG_AMOUNT',
            'DDD',
            'AMA',
            'ADDI_C',
            'BOLL',
            'OSC',
            'MAOSC',
            'LONG60',
            'RSI3',
            'SHORT60']