BTC=['btcbtcusd','btcbchusd']

GOLD=['GC','XAU']

MONEY=['USDCNY','USDJPY','USDEUR','USDGBP']

CN_INDEX=['SH000001','SZ399006','SZ399001',
       'HKHSI','HKHSCCI','HKHSCEI']

US_INDEX=['.DJI','.IXIC','.INX']

FUTURE=[]