BTC=['btcbtcusd','btcbchusd']

GOLD=['GC','XAU','CL','NG','S']

MONEY=['USDCNY','USDJPY','USDEUR','USDGBP','USDHKD','USDAUD','USDCAD']

DOLLAR = ['DINIW']

CN_INDEX=['SH000001','SZ399006','SZ399001',
       'HKHSI','HKHSCCI','HKHSCEI']

US_INDEX=['.DJI','.IXIC','.INX']

GLOBAL = ['DAX','NKY','UKX', 'CAC40', 'AS51', 'GSPTSE']

FUTURE=['ZC0','JM0','I0','CU0','P0','SR0','CF0']

FA_STOCK = ['APPLE','']