from QUANTTOOLS.FactorTools.SingelePeriodFactorTest import SingelePeriodFactorTest
from QUANTTOOLS.FactorTools.MultiPeriodFactorTest import MultiPeriodFactorTest

from QUANTTOOLS.FactorTools.base_func import get_quant_data
