from .concat_predict import make_prediction, save_prediction, load_prediction, check_prediction,make_stockprediction,make_indexprediction
from .prediction_report import prediction_report
from .runnig_base import predict_base