import cx_Oracle
import pandas as pd
from  QUANTAXIS.QAUtil import (QA_util_date_stamp,QA_util_today_str,
                               QA_util_get_trade_range,QA_util_get_last_day,
                               QA_util_if_trade)
from QUANTAXIS.QAUtil import QA_util_log_info
from QUANTTOOLS.QAStockETL.QAData.database_settings import (Oracle_Database, Oracle_User, Oracle_Password, Oralce_Server, MongoDB_Server, MongoDB_Database)

ORACLE_PATH2 = '{user}/{password}@{server}:1521/{database}'.format(database = Oracle_Database, password = Oracle_Password, server = Oralce_Server, user = Oracle_User)


def QA_util_process_stock_financial(ui_log= None):
    QA_util_log_info(
        '##JOB01 Now Etl Stock Financial ==== {}'.format(QA_util_today_str()), ui_log)
    sql1 = '''create table stock_financial_TTM as
 with f as
 (select code,
       report_date,
       totalAssets,
       intangibleAssets,
       goodwill,
       longTermDeferredExpenses,
       fixedAssets,
       interestReceivables,
       inventory,
       moneyFunds,
       accountsReceivables,
       prepayments,
       totalLiquidAssets,
       interestPayable,
       accountsPayable,
       totalCurrentLiabilities,
       totalLiabilities,
       operatingRevenue,
       operatingCosts,
       taxAndSurcharges,
       operatingProfit,
       netProfit,
       financialCosts,
       netProAftExtrGainLoss,
       cashOutOperaActiv,
       netCashOperatActiv,
       cashOutInvestActiv,
       deprecForFixedAssets,
       subsidyIncome,
       interestCoverageRatio,
       totalProfit,
       cashPayDistDivProf,
       cashPayLongTermAssets,
       dispCashLongTermAssets,
       DECODE(interestCoverageRatio,
              1,
              netProfit,
              netProfit / (interestCoverageRatio - 1)) as interest,
       cashPayDistDivProf -
       DECODE(interestCoverageRatio,
              1,
              netProfit,
              netProfit / (interestCoverageRatio - 1)) as cashPayDistDiv,
       currentRatio,
       acidTestRatio,
       cashRatio,
       salesCosts,
       managementCosts,
       incomeTax,
       assestsDevaluation,
       provisionForAssetsLosses,
       interCompanyReceivables,
       explorationCosts,
       totalOwnersEquity
  from (select code,
               report_date,
               max(totalAssets) as totalAssets,
               max(intangibleAssets) as intangibleAssets,
               max(goodwill) as goodwill,
               max(longTermDeferredExpenses) as longTermDeferredExpenses,
               max(fixedAssets) as fixedAssets,
               max(interestReceivables) as interestReceivables,
               max(inventory) as inventory,
               max(moneyFunds) as moneyFunds,
               max(accountsReceivables) as accountsReceivables,
               max(prepayments) as prepayments,
               max(totalLiquidAssets) as totalLiquidAssets,
               max(interestPayable) as interestPayable,
               max(accountsPayable) as accountsPayable,
               max(totalCurrentLiabilities) as totalCurrentLiabilities,
               max(totalLiabilities) as totalLiabilities,
               max(operatingRevenue) as operatingRevenue,
               max(operatingCosts) as operatingCosts,
               max(taxAndSurcharges) as taxAndSurcharges,
               max(operatingProfit) as operatingProfit,
               max(netProfit) as netProfit,
               max(financialCosts) as financialCosts,
               max(netProAftExtrGainLoss) as netProAftExtrGainLoss,
               max(cashOutOperaActiv) as cashOutOperaActiv,
               max(netCashOperatActiv) as netCashOperatActiv,
               max(cashOutInvestActiv) as cashOutInvestActiv,
               max(deprecForFixedAssets) as deprecForFixedAssets,
               max(subsidyIncome) as subsidyIncome,
               max(interestCoverageRatio) as interestCoverageRatio,
               max(totalProfit) as totalProfit,
               max(cashPayDistDivProf) as cashPayDistDivProf,
               max(cashPayLongTermAssets) as cashPayLongTermAssets,
               max(dispCashLongTermAssets) as dispCashLongTermAssets,
               max(currentRatio) as currentRatio,
               max(acidTestRatio) as acidTestRatio,
               max(cashRatio) as cashRatio,
               max(salesCosts) as salesCosts,
               max(managementCosts) as managementCosts,
               max(incomeTax) as incomeTax,
               max(assestsDevaluation) as assestsDevaluation,
               max(provisionForAssetsLosses) as provisionForAssetsLosses,
               max(interCompanyReceivables) as interCompanyReceivables,
               max(explorationCosts) as explorationCosts,
               max(totalOwnersEquity) as totalOwnersEquity
          from (select code,
                       to_date(report_date, 'yyyy-mm-dd') as report_date,
                       totalAssets,
                       intangibleAssets,
                       goodwill,
                       longTermDeferredExpenses,
                       fixedAssets,
                       interestReceivables,
                       inventory,
                       moneyFunds,
                       accountsReceivables,
                       prepayments,
                       totalLiquidAssets,
                       interestPayable,
                       accountsPayable,
                       totalCurrentLiabilities,
                       totalLiabilities,
                       operatingRevenue,
                       operatingCosts,
                       taxAndSurcharges,
                       operatingProfit,
                       netProfitsBelToParComOwner as netProfit,
                       financialCosts,
                       netProAftExtrGainLoss,
                       cashOutOperaActiv,
                       netCashOperatActiv,
                       cashOutInvestActiv,
                       deprecForFixedAssets,
                       subsidyIncome,
                       interestCoverageRatio,
                       totalProfit,
                       cashPayDistDivProf,
                       cashPayLongTermAssets,
                       dispCashLongTermAssets,
                       currentRatio,
                       acidTestRatio,
                       cashRatio,
                       salesCosts,
                       managementCosts,
                       incomeTax,
                       assestsDevaluation,
                       provisionForAssetsLosses,
                       interCompanyReceivables,
                       explorationCosts,
                       totalOwnersEquity
                  from stock_financial
                union all
                select code,
                       report_date,
                       totalAssets,
                       intangibleAssets,
                       goodwill,
                       longTermDeferredExpenses,
                       fixedAssets,
                       interestReceivables,
                       inventory,
                       moneyFunds,
                       accountsReceivables,
                       prepayments,
                       totalLiquidAssets,
                       interestPayable,
                       accountsPayable,
                       totalCurrentLiabilities,
                       totalLiabilities,
                       operatingRevenue,
                       operatingCosts,
                       taxAndSurcharges,
                       operatingProfit,
                       netProfitsBelToParComOwner as netProfit,
                       financialCosts,
                       netProAftExtrGainLoss,
                       cashOutOperaActiv,
                       netCashOperatActiv,
                       cashOutInvestActiv,
                       deprecForFixedAssets,
                       subsidyIncome,
                       case
                         when financialCosts <= 0 then
                          100
                         else
                          (operatingProfit + financialCosts) / financialCosts
                       end as interestCoverageRatio,
                       totalProfit,
                       cashPayDistDivProf,
                       cashPayLongTermAssets,
                       dispCashLongTermAssets,
                       case
                         when totalCurrentLiabilities <= 0 then
                          100
                         else
                          totalLiquidAssets / totalCurrentLiabilities
                       end as currentRatio,
                       case
                         when totalCurrentLiabilities <= 0 then
                          100
                         else
                          (totalLiquidAssets - inventory) /
                          totalCurrentLiabilities
                       end as acidTestRatio,
                       case
                         when totalCurrentLiabilities <= 0 then
                          100
                         else
                          (totalLiquidAssets - inventory - accountsReceivables) /
                          totalCurrentLiabilities
                       end as cashRatio,
                       salesCosts,
                       managementCosts,
                       incomeTax,
                       assestsDevaluation,
                       provisionForAssetsLosses,
                       null as interCompanyReceivables,
                       null as explorationCosts,
                       totalOwnersEquity
                  from stock_financial_wy) h
         group by code, report_date) g)
  SELECT A.CODE,
A.REPORT_DATE,
ADD_MONTHS(A.REPORT_DATE, -12) AS YOY,
ADD_MONTHS(A.REPORT_DATE, -3) AS LAG1,
TRUNC(A.REPORT_DATE, 'YEAR') - 1 AS LY,
ADD_MONTHS(trunc(ADD_MONTHS(A.REPORT_DATE, 0),'year'),3) -1 AS BG,
(A.TOTALASSETS + bg.TOTALASSETS) / 2 AS AVGTOTALASSETS,
(A.FIXEDASSETS + bg.FIXEDASSETS) / 2 AS AVGFIXEDASSETS,
(A.GOODWILL + bg.GOODWILL) / 2 AS AVGGOODWILL,
(A.INVENTORY + bg.INVENTORY) / 2 AS AVGINVENTORY,
(A.TOTALLIQUIDASSETS + bg.TOTALLIQUIDASSETS) / 2AS AVGTOTALLIQUIDASSETS,
(A.TOTALLIABILITIES + bg.TOTALLIABILITIES) / 2 AS AVGTOTALLIABILITIES,
(A.ACCOUNTSRECEIVABLES + bg.ACCOUNTSRECEIVABLES) / 2 AS AVGACCOUNTSRECEIVABLES,
(A.INTERCOMPANYRECEIVABLES + bg.INTERCOMPANYRECEIVABLES) / 2 AS AVGINTERCOMPANYRECEIVABLES,
(A.PREPAYMENTS + bg.PREPAYMENTS) / 2 AS AVGPREPAYMENTS,
(A.ACCOUNTSPAYABLE + bg.ACCOUNTSPAYABLE) / 2 AS AVGACCOUNTSPAYABLE,
(A.TOTALCURRENTLIABILITIES + bg.TOTALCURRENTLIABILITIES) / 2 AS AVGTOTALCURRENTLIABILITIES,
(A.totalOwnersEquity + bg.totalOwnersEquity) / 2 AS AVGtotalOwnersEquity,
ly.OPERATINGREVENUE - yoy.OPERATINGREVENUE + A.OPERATINGREVENUE AS OPERATINGREVENUE_TTM,
ly.OPERATINGCOSTS - yoy.OPERATINGCOSTS + A.OPERATINGCOSTS AS OPERATINGCOSTS_TTM,
ly.TAXANDSURCHARGES - yoy.TAXANDSURCHARGES + A.TAXANDSURCHARGES AS TAXANDSURCHARGES_TTM,
ly.SALESCOSTS - yoy.SALESCOSTS + A.SALESCOSTS AS SALESCOSTS_TTM,
ly.MANAGEMENTCOSTS - yoy.MANAGEMENTCOSTS + A.MANAGEMENTCOSTS AS MANAGEMENTCOSTS_TTM,
ly.EXPLORATIONCOSTS - yoy.EXPLORATIONCOSTS + A.EXPLORATIONCOSTS AS EXPLORATIONCOSTS_TTM,
ly.FINANCIALCOSTS - yoy.FINANCIALCOSTS + A.FINANCIALCOSTS AS FINANCIALCOSTS_TTM,
ly.ASSESTSDEVALUATION - yoy.ASSESTSDEVALUATION + A.ASSESTSDEVALUATION AS ASSESTSDEVALUATION_TTM,
ly.OPERATINGPROFIT - yoy.OPERATINGPROFIT + A.OPERATINGPROFIT AS OPERATINGPROFIT_TTM,
ly.TOTALPROFIT - yoy.TOTALPROFIT + A.TOTALPROFIT AS TOTALPROFIT_TTM,
ly.INCOMETAX - yoy.INCOMETAX + A.INCOMETAX AS INCOMETAX_TTM,
ly.NETPROFIT - yoy.NETPROFIT + A.NETPROFIT AS NETPROFIT_TTM,
ly.NETPROAFTEXTRGAINLOSS - yoy.NETPROAFTEXTRGAINLOSS + A.NETPROAFTEXTRGAINLOSS AS NETPROAFTEXTRGAINLOSS_TTM,
ly.INTEREST - yoy.INTEREST + A.INTEREST AS INTEREST_TTM,
ly.DEPRECFORFIXEDASSETS - yoy.DEPRECFORFIXEDASSETS + A.DEPRECFORFIXEDASSETS AS DEPRECFORFIXEDASSETS_TTM,
ly.NETCASHOPERATACTIV - yoy.NETCASHOPERATACTIV + A.NETCASHOPERATACTIV AS NETCASHOPERATACTIV_TTM,
ly.CASHOUTINVESTACTIV - yoy.CASHOUTINVESTACTIV + A.CASHOUTINVESTACTIV AS CASHOUTINVESTACTIV_TTM,
A.MONEYFUNDS,
A.TOTALASSETS,
A.ACCOUNTSPAYABLE,
A.totalOwnersEquity,
A.INTEREST,
A.INTANGIBLEASSETS,
A.SALESCOSTS,
A.MANAGEMENTCOSTS,
A.EXPLORATIONCOSTS,
A.INCOMETAX,
A.INTERCOMPANYRECEIVABLES,
A.GOODWILL,
A.LONGTERMDEFERREDEXPENSES,
A.FIXEDASSETS,
A.INTERESTRECEIVABLES,
A.INVENTORY,
A.ACCOUNTSRECEIVABLES,
A.PREPAYMENTS,
A.TOTALLIQUIDASSETS,
A.INTERESTPAYABLE,
A.TOTALCURRENTLIABILITIES,
A.TOTALLIABILITIES,
A.OPERATINGREVENUE,
A.OPERATINGCOSTS,
A.TAXANDSURCHARGES,
A.OPERATINGPROFIT,
A.NETPROFIT,
A.FINANCIALCOSTS,
A.NETPROAFTEXTRGAINLOSS,
A.CASHOUTINVESTACTIV,
A.CASHOUTOPERAACTIV,
A.NETCASHOPERATACTIV,
A.DEPRECFORFIXEDASSETS,
A.SUBSIDYINCOME,
A.INTERESTCOVERAGERATIO,
A.TOTALPROFIT,
A.CASHPAYDISTDIVPROF,
A.CASHPAYLONGTERMASSETS,
A.NETPROFIT - A.NETPROAFTEXTRGAINLOSS AS EXTRGAINLOSS
  from (select * from f) A
  left join f yoy
    on yoy.report_date = add_months(A.report_date, -12)
   and A.code = yoy.code
  left join f loq
    on loq.report_date = add_months(A.report_date, -3)
   and A.code = loq.code
  left join f ly
    on ly.report_date = trunc(A.report_date, 'year') - 1
   and A.code = ly.code
  left join f bg
    on bg.report_date = ADD_MONTHS(trunc(ADD_MONTHS(A.REPORT_DATE, 0),'year'),3) -1
   and A.code = bg.code
     '''

    sql2='''create table stock_financial_analysis as 
with t as
 (select code,
         report_date,
         totalAssets,
         avgTotalAssets,
         fixedAssets,
         avgFixedAssets,
         goodwill,
         avgGoodwill,
         inventory,
         moneyFunds,
         accountsPayable,
         avgAccountsPayable,
         avgInventory,
         totalLiquidAssets,
         avgTotalLiquidAssets,
         totalLiabilities,
         avgTotalLiabilities,
         accountsReceivables,
         avgAccountsReceivables,
         interCompanyReceivables,
         avgInterCompanyReceivables,
         prepayments,
         avgPrepayments,
         totalCurrentLiabilities,
         avgTotalCurrentLiabilities,
         operatingRevenue,
         operatingCosts,
         taxAndSurcharges,
         salesCosts,
         managementCosts,
         explorationCosts,
         financialCosts,
         operatingProfit,
         totalProfit,
         incomeTax,
         netProfit,
         netProAftExtrGainLoss,
         interest,
         deprecForFixedAssets,
         netCashOperatActiv,
         cashOutInvestActiv,
         netProfit_TTM,
         netProAftExtrGainLoss_TTM,
         case
           when avgTotalAssets <= 0 then
            0
           else
            netProfit / avgTotalAssets
         end as ROA,
         case
           when avgTotalAssets <= 0 then
            0
           else
            netProfit_TTM / avgTotalAssets
         end as ROA_TTM,
         case
           when AVGTOTALOWNERSEQUITY <= 0 then
            0
           else
            netProfit / AVGTOTALOWNERSEQUITY
         end as ROE,
         case
           when AVGTOTALOWNERSEQUITY <= 0 then
            0
           else
            netProfit_TTM / AVGTOTALOWNERSEQUITY
         end as ROE_TTM,
         case
           when AVGTOTALOWNERSEQUITY <= 0 then
            0
           else
            netProAftExtrGainLoss / AVGTOTALOWNERSEQUITY
         end as netROE,
         case
           when AVGTOTALOWNERSEQUITY <= 0 then
            0
           else
            netProAftExtrGainLoss_TTM / AVGTOTALOWNERSEQUITY
         end as netROE_TTM,
         case
           when operatingCosts <= 0 then
            0
           else
            operatingRevenue / operatingCosts - 1
         end as grossMargin,
         case
           when operatingRevenue <= 0 then
            0
           else
            netProAftExtrGainLoss / operatingRevenue
         end as NetProfitMarginonSales,
         
         case
           when netProAftExtrGainLoss <= 0 then
            0
           else
            incomeTax / netProAftExtrGainLoss
         end as incomeTaxRatio,
         case
           when operatingRevenue <= 0 then
            0
           else
            cashOutInvestActiv / operatingRevenue
         end as reinvestedIncomeRatio,
         
         case
           when operatingRevenue <= 0 then
            0
           else
            deprecForFixedAssets / operatingRevenue
         end as depreciationRatio,
         case
           when operatingRevenue <= 0 then
            0
           else
            (accountsReceivables + inventory - accountsPayable) /
            operatingRevenue
         end AS operatingCashRatio
         ---运营模式
        ,
         case
           when avgTotalAssets - avgGoodwill <= 0 then
            0
           else
            avgFixedAssets / (avgTotalAssets - avgGoodwill)
         end AS avgFiexdOfAssets,
         case
           when avgTotalAssets <= 0 then
            0
           else
            avgFixedAssets / avgTotalAssets
         end AS fiexdOfAssets,
         case
           when avgTotalCurrentLiabilities <= 0 then
            0
           else
            (avgTotalLiquidAssets - avgInventory - avgPrepayments) /
            avgTotalCurrentLiabilities
         end AS acidTestRatio
         
         ---运营效率
        ,
         case
           when avgAccountsReceivables <= 0 then
            0
           else
            operatingRevenue / avgAccountsReceivables
         end as turnoverRatioOfReceivable,
         case
           when avgInventory <= 0 then
            0
           else
            operatingRevenue / avgInventory
         end as turnoverRatioOfInventory,
         case
           when avgTotalAssets <= 0 then
            0
           else
            operatingRevenue / avgTotalAssets
         end as turnoverRatioOfTotalAssets,
         case
           when operatingRevenue - totalProfit <= 0 then
            0
           else
            deprecForFixedAssets / (operatingRevenue - totalProfit)
         end as depreciationOftotalCosts
         
         ---利润质量
        ,
         case
           when netProfit <= 0 then
            0
           else
            netCashOperatActiv / netProfit
         end AS cashOfnetProfit,
         case
           when interest <= 0 then
            0
           else
            netCashOperatActiv / interest
         end as cashOfinterest
         
         ---偿债能力
        ,
         case
           when totalAssets <= 0 then
            0
           else
            totalLiabilities / totalAssets
         end as assetsLiabilitiesRatio,
         case
           when totalCurrentLiabilities <= 0 then
            0
           else
            totalLiabilities / totalCurrentLiabilities
         end as tangibleAssetDebtRatio,
         case
           when totalCurrentLiabilities <= 0 then
            0
           else
            (totalLiquidAssets - inventory - accountsReceivables -
            prepayments) / totalCurrentLiabilities
         end AS cashRatio
    from stock_financial_TTM),
rp as
 (select code,
         report_date,
         min(send_date) as send_date,
         max(end_date) as end_date
    from (select code,
                 to_date(report_date, 'yyyy-mm-dd') as report_date,
                 to_date(send_date, 'yyyy-mm-dd') as send_date,
                 to_date(COALESCE(lag(send_date)
                                  over(partition by code order by report_date desc),
                                  to_char(sysdate, 'yyyy-mm-dd')),
                         'yyyy-mm-dd') as end_date
            from (select code,
                         to_char(report_date, 'yyyy-mm-dd') as report_date,
                         to_char(MIN(real_date), 'yyyy-mm-dd') as send_date
                    from stock_calendar
                   group by code, report_date
                  union all
                  select code,
                         CASE
                           WHEN to_char(to_date(timetomarket, 'yyyymmdd'), 'Q') = 1 THEN
                            to_char(trunc(to_date(timetomarket, 'yyyymmdd'),
                                          'year') - 1,
                                    'yyyy-mm-dd')
                           when to_char(to_date(timetomarket, 'yyyymmdd'), 'Q') = 2 then
                            to_char(to_date(concat(to_char(to_date(timetomarket,
                                                                   'yyyymmdd'),
                                                           'yyyy'),
                                                   '0331'),
                                            'yyyymmdd'),
                                    'yyyy-mm-dd')
                           when to_char(to_date(timetomarket, 'yyyymmdd'), 'Q') = 3 then
                            to_char(to_date(concat(to_char(to_date(timetomarket,
                                                                   'yyyymmdd'),
                                                           'yyyy'),
                                                   '0630'),
                                            'yyyymmdd'),
                                    'yyyy-mm-dd')
                           when to_char(to_date(timetomarket, 'yyyymmdd'), 'Q') = 4 then
                            to_char(to_date(concat(to_char(to_date(timetomarket,
                                                                   'yyyymmdd'),
                                                           'yyyy'),
                                                   '0930'),
                                            'yyyymmdd'),
                                    'yyyy-mm-dd')
                           else
                            null
                         end as report_date,
                         to_char(to_date(timetomarket, 'yyyymmdd') - 1,
                                 'yyyy-mm-dd') as send_date
                    from stock_info
                   where length(timetomarket) = 8) h) g
   group by code, report_date),
res as
 (SELECT A.CODE,
         INDUSTRY,
         NAME,
         AREA,
         A.REPORT_DATE,
         ADD_MONTHS(A.REPORT_DATE, -12) AS LASTYEAR,
         ADD_MONTHS(A.REPORT_DATE, -3) AS LAG1,
         ADD_MONTHS(A.REPORT_DATE, -24) AS LAST2YEAR,
         ADD_MONTHS(A.REPORT_DATE, -36) AS LAST3YEAR,
         ADD_MONTHS(A.REPORT_DATE, -48) AS LAST4YEAR,
         ADD_MONTHS(A.REPORT_DATE, -60) AS LAST5YEAR,
         SEND_DATE,
         END_DATE,
         A.TOTALASSETS,
         A.AVGTOTALASSETS,
         A.FIXEDASSETS,
         A.AVGFIXEDASSETS,
         A.GOODWILL,
         A.AVGGOODWILL,
         A.INVENTORY,
         A.MONEYFUNDS,
         A.ACCOUNTSPAYABLE,
         A.AVGACCOUNTSPAYABLE,
         A.AVGINVENTORY,
         A.TOTALLIQUIDASSETS,
         A.AVGTOTALLIQUIDASSETS,
         A.TOTALLIABILITIES,
         A.AVGTOTALLIABILITIES,
         A.ACCOUNTSRECEIVABLES,
         A.AVGACCOUNTSRECEIVABLES,
         A.INTERCOMPANYRECEIVABLES,
         A.AVGINTERCOMPANYRECEIVABLES,
         A.PREPAYMENTS,
         A.AVGPREPAYMENTS,
         A.TOTALCURRENTLIABILITIES,
         A.AVGTOTALCURRENTLIABILITIES,
         A.NETCASHOPERATACTIV,
         A.CASHOUTINVESTACTIV,
          A.operatingRevenue,
          A.operatingCosts,
          A.taxAndSurcharges,
          A.salesCosts,
          A.managementCosts,
          A.explorationCosts,
          A.financialCosts,
          A.operatingProfit,
          A.totalProfit,
         A.incomeTax,
         A.NETPROFIT,
         A.NETPROFIT_TTM,
         A.NETPROAFTEXTRGAINLOSS,
         A.NETPROAFTEXTRGAINLOSS_TTM,
         A.ROA,
         A.ROA_TTM,
         A.ROE,
         A.ROE_TTM,
         A.GROSSMARGIN,
         A.NETROE,
         A.NETROE_TTM,
         A.NETPROFITMARGINONSALES,
         A.INCOMETAXRATIO,
         A.REINVESTEDINCOMERATIO,
         A.DEPRECIATIONRATIO,
         A.OPERATINGCASHRATIO,
         A.AVGFIEXDOFASSETS,
         A.FIEXDOFASSETS,
         A.ACIDTESTRATIO,
         A.TURNOVERRATIOOFRECEIVABLE,
         A.TURNOVERRATIOOFINVENTORY,
         A.TURNOVERRATIOOFTOTALASSETS,
         A.DEPRECIATIONOFTOTALCOSTS,
         A.CASHOFNETPROFIT,
         A.CASHOFINTEREST,
         A.ASSETSLIABILITIESRATIO,
         A.TANGIBLEASSETDEBTRATIO,
         A.CASHRATIO
    FROM T A
    LEFT JOIN RP C
      ON C.REPORT_DATE = A.REPORT_DATE
     AND A.CODE = C.CODE
    LEFT JOIN (SELECT CODE,
                     MAX(TDX) as INDUSTRY,
                     MAX(NAME) as NAME,
                     MAX(AREA) as AREA
                from STOCK_INFO
               GROUP BY CODE) F
      ON A.CODE = F.CODE)
SELECT A.CODE,
       A.INDUSTRY,
       A.NAME,
       A.AREA,
       A.REPORT_DATE,
       ADD_MONTHS(A.REPORT_DATE, -12) AS LASTYEAR,
       ADD_MONTHS(A.REPORT_DATE, -3) AS LAG1,
       ADD_MONTHS(A.REPORT_DATE, -24) AS LAST2YEAR,
       ADD_MONTHS(A.REPORT_DATE, -36) AS LAST3YEAR,
       ADD_MONTHS(A.REPORT_DATE, -48) AS LAST4YEAR,
       ADD_MONTHS(A.REPORT_DATE, -60) AS LAST5YEAR,
       A.SEND_DATE,
       A.END_DATE,
       A.TOTALASSETS,
       A.AVGTOTALASSETS,
       A.FIXEDASSETS,
       A.AVGFIXEDASSETS,
       A.GOODWILL,
       A.AVGGOODWILL,
       A.INVENTORY,
       A.MONEYFUNDS,
       A.ACCOUNTSPAYABLE,
       A.AVGACCOUNTSPAYABLE,
       A.AVGINVENTORY,
       A.TOTALLIQUIDASSETS,
       A.AVGTOTALLIQUIDASSETS,
       A.TOTALLIABILITIES,
       A.AVGTOTALLIABILITIES,
       A.ACCOUNTSRECEIVABLES,
       A.AVGACCOUNTSRECEIVABLES,
       A.INTERCOMPANYRECEIVABLES,
       A.AVGINTERCOMPANYRECEIVABLES,
       A.PREPAYMENTS,
       A.AVGPREPAYMENTS,
       A.TOTALCURRENTLIABILITIES,
       A.AVGTOTALCURRENTLIABILITIES,
       A.NETCASHOPERATACTIV,
       A.CASHOUTINVESTACTIV,
       A.operatingRevenue,
       A.operatingCosts,
       A.taxAndSurcharges,
       A.salesCosts,
       A.managementCosts,
       A.explorationCosts,
       A.financialCosts,
       A.operatingProfit,
       A.totalProfit,
         A.incomeTax,
       A.NETPROFIT,
       A.NETPROFIT_TTM,
       A.NETPROAFTEXTRGAINLOSS,
       A.NETPROAFTEXTRGAINLOSS_TTM,
       A.ROA,
       A.ROA_TTM,
       A.ROE,
       A.ROE_TTM,
       A.GROSSMARGIN,
       A.NETROE,
       A.NETROE_TTM,
       A.NETPROFITMARGINONSALES,
       A.INCOMETAXRATIO,
       A.REINVESTEDINCOMERATIO,
       A.DEPRECIATIONRATIO,
       A.OPERATINGCASHRATIO,
       A.AVGFIEXDOFASSETS,
       A.FIEXDOFASSETS,
       A.ACIDTESTRATIO,
       A.TURNOVERRATIOOFRECEIVABLE,
       A.TURNOVERRATIOOFINVENTORY,
       A.TURNOVERRATIOOFTOTALASSETS,
       A.DEPRECIATIONOFTOTALCOSTS,
       A.CASHOFNETPROFIT,
       A.CASHOFINTEREST,
       A.ASSETSLIABILITIESRATIO,
       A.TANGIBLEASSETDEBTRATIO,
       A.CASHRATIO,
       B.TOTALASSETS as TOTALASSETS_YOY,
       B.AVGTOTALASSETS as AVGTOTALASSETS_YOY,
       B.FIXEDASSETS as FIXEDASSETS_YOY,
       B.AVGFIXEDASSETS as AVGFIXEDASSETS_YOY,
       B.GOODWILL as GOODWILL_YOY,
       B.AVGGOODWILL as AVGGOODWILL_YOY,
       B.INVENTORY as INVENTORY_YOY,
       B.MONEYFUNDS as MONEYFUNDS_YOY,
       B.ACCOUNTSPAYABLE as ACCOUNTSPAYABLE_YOY,
       B.AVGACCOUNTSPAYABLE as AVGACCOUNTSPAYABLE_YOY,
       B.AVGINVENTORY as AVGINVENTORY_YOY,
       B.TOTALLIQUIDASSETS as TOTALLIQUIDASSETS_YOY,
       B.AVGTOTALLIQUIDASSETS as AVGTOTALLIQUIDASSETS_YOY,
       B.TOTALLIABILITIES as TOTALLIABILITIES_YOY,
       B.AVGTOTALLIABILITIES as AVGTOTALLIABILITIES_YOY,
       B.ACCOUNTSRECEIVABLES as ACCOUNTSRECEIVABLES_YOY,
       B.AVGACCOUNTSRECEIVABLES as AVGACCOUNTSRECEIVABLES_YOY,
       B.INTERCOMPANYRECEIVABLES as INTERCOMPANYRECEIVABLES_YOY,
       B.AVGINTERCOMPANYRECEIVABLES as AVGINTERCOMPANYRECEIVABLES_YOY,
       B.PREPAYMENTS as PREPAYMENTS_YOY,
       B.AVGPREPAYMENTS as AVGPREPAYMENTS_YOY,
       B.TOTALCURRENTLIABILITIES as TOTALCURRENTLIABILITIES_YOY,
       B.AVGTOTALCURRENTLIABILITIES as AVGTOTALCURRENTLIABILITIES_YOY,
       B.NETCASHOPERATACTIV as NETCASHOPERATACTIV_YOY,
       B.CASHOUTINVESTACTIV as CASHOUTINVESTACTIV_YOY,
       B.operatingRevenue as operatingRevenue_YOY,
       B.operatingCosts as operatingCosts_YOY,
       B.taxAndSurcharges as taxAndSurcharges_YOY,
       B.salesCosts as salesCosts_YOY,
       B.managementCosts as managementCosts_YOY,
       B.explorationCosts as explorationCosts_YOY,
       B.financialCosts as financialCosts_YOY,
       B.operatingProfit as operatingProfit_YOY,
               B.totalProfit as totalProfit_YOY,
        B.incomeTax as incomeTax_YOY,
       B.NETPROFIT as NETPROFIT_YOY,
       B.NETPROFIT_TTM as NETPROFIT_TTM_YOY,
       B.NETPROAFTEXTRGAINLOSS as NETPROAFTEXTRGAINLOSS_YOY,
       B.NETPROAFTEXTRGAINLOSS_TTM as NETPROAFTEXTRGAINLOSS_TTM_YOY,
       B.ROA as ROA_YOY,
       B.ROA_TTM as ROA_TTM_YOY,
       B.ROE as ROE_YOY,
       B.ROE_TTM as ROE_TTM_YOY,
       B.GROSSMARGIN as GROSSMARGIN_YOY,
       B.NETROE as NETROE_YOY,
       B.NETROE_TTM as NETROE_TTM_YOY,
       B.NETPROFITMARGINONSALES as NETPROFITMARGINONSALES_YOY,
       B.INCOMETAXRATIO as INCOMETAXRATIO_YOY,
       B.REINVESTEDINCOMERATIO as REINVESTEDINCOMERATIO_YOY,
       B.DEPRECIATIONRATIO as DEPRECIATIONRATIO_YOY,
       B.OPERATINGCASHRATIO as OPERATINGCASHRATIO_YOY,
       B.AVGFIEXDOFASSETS as AVGFIEXDOFASSETS_YOY,
       B.FIEXDOFASSETS as FIEXDOFASSETS_YOY,
       B.ACIDTESTRATIO as ACIDTESTRATIO_YOY,
       B.TURNOVERRATIOOFRECEIVABLE as TURNOVERRATIOOFRECEIVABLE_YOY,
       B.TURNOVERRATIOOFINVENTORY as TURNOVERRATIOOFINVENTORY_YOY,
       B.TURNOVERRATIOOFTOTALASSETS as TURNOVERRATIOOFTOTALASSETS_YOY,
       B.DEPRECIATIONOFTOTALCOSTS as DEPRECIATIONOFTOTALCOSTS_YOY,
       B.CASHOFNETPROFIT as CASHOFNETPROFIT_YOY,
       B.CASHOFINTEREST as CASHOFINTEREST_YOY,
       B.ASSETSLIABILITIESRATIO as ASSETSLIABILITIESRATIO_YOY,
       B.TANGIBLEASSETDEBTRATIO as TANGIBLEASSETDEBTRATIO_YOY,
       B.CASHRATIO as CASHRATIO_YOY,
       D.TOTALASSETS as TOTALASSETS_LQ,
       D.AVGTOTALASSETS as AVGTOTALASSETS_LQ,
       D.FIXEDASSETS as FIXEDASSETS_LQ,
       D.AVGFIXEDASSETS as AVGFIXEDASSETS_LQ,
       D.GOODWILL as GOODWILL_LQ,
       D.AVGGOODWILL as AVGGOODWILL_LQ,
       D.INVENTORY as INVENTORY_LQ,
       D.MONEYFUNDS as MONEYFUNDS_LQ,
       D.ACCOUNTSPAYABLE as ACCOUNTSPAYABLE_LQ,
       D.AVGACCOUNTSPAYABLE as AVGACCOUNTSPAYABLE_LQ,
       D.AVGINVENTORY as AVGINVENTORY_LQ,
       D.TOTALLIQUIDASSETS as TOTALLIQUIDASSETS_LQ,
       D.AVGTOTALLIQUIDASSETS as AVGTOTALLIQUIDASSETS_LQ,
       D.TOTALLIABILITIES as TOTALLIABILITIES_LQ,
       D.AVGTOTALLIABILITIES as AVGTOTALLIABILITIES_LQ,
       D.ACCOUNTSRECEIVABLES as ACCOUNTSRECEIVABLES_LQ,
       D.AVGACCOUNTSRECEIVABLES as AVGACCOUNTSRECEIVABLES_LQ,
       D.INTERCOMPANYRECEIVABLES as INTERCOMPANYRECEIVABLES_LQ,
       D.AVGINTERCOMPANYRECEIVABLES as AVGINTERCOMPANYRECEIVABLES_LQ,
       D.PREPAYMENTS as PREPAYMENTS_LQ,
       D.AVGPREPAYMENTS as AVGPREPAYMENTS_LQ,
       D.TOTALCURRENTLIABILITIES as TOTALCURRENTLIABILITIES_LQ,
       D.AVGTOTALCURRENTLIABILITIES as AVGTOTALCURRENTLIABILITIES_LQ,
       D.NETCASHOPERATACTIV as NETCASHOPERATACTIV_LQ,
       D.CASHOUTINVESTACTIV as CASHOUTINVESTACTIV_LQ,
       D.operatingRevenue as operatingRevenue_LQ,
        D.operatingCosts as operatingCosts_LQ,
        D.taxAndSurcharges as taxAndSurcharges_LQ,
        D.salesCosts as salesCosts_LQ,
        D.managementCosts as managementCosts_LQ,
        D.explorationCosts as explorationCosts_LQ,
        D.financialCosts as financialCosts_LQ,
        D.operatingProfit as operatingProfit_LQ,
        D.totalProfit as totalProfit_LQ,
        D.incomeTax as incomeTax_LQ,
       D.NETPROFIT as NETPROFIT_LQ,
       D.NETPROFIT_TTM as NETPROFIT_TTM_LQ,
       D.NETPROAFTEXTRGAINLOSS as NETPROAFTEXTRGAINLOSS_LQ,
       D.NETPROAFTEXTRGAINLOSS_TTM as NETPROAFTEXTRGAINLOSS_TTM_LQ,
       D.ROA as ROA_LQ,
       D.ROA_TTM as ROA_TTM_LQ,
       D.ROE as ROE_LQ,
       D.ROE_TTM as ROE_TTM_LQ,
       D.GROSSMARGIN as GROSSMARGIN_LQ,
       D.NETROE as NETROE_LQ,
       D.NETROE_TTM as NETROE_TTM_LQ,
       D.NETPROFITMARGINONSALES as NETPROFITMARGINONSALES_LQ,
       D.INCOMETAXRATIO as INCOMETAXRATIO_LQ,
       D.REINVESTEDINCOMERATIO as REINVESTEDINCOMERATIO_LQ,
       D.DEPRECIATIONRATIO as DEPRECIATIONRATIO_LQ,
       D.OPERATINGCASHRATIO as OPERATINGCASHRATIO_LQ,
       D.AVGFIEXDOFASSETS as AVGFIEXDOFASSETS_LQ,
       D.FIEXDOFASSETS as FIEXDOFASSETS_LQ,
       D.ACIDTESTRATIO as ACIDTESTRATIO_LQ,
       D.TURNOVERRATIOOFRECEIVABLE as TURNOVERRATIOOFRECEIVABLE_LQ,
       D.TURNOVERRATIOOFINVENTORY as TURNOVERRATIOOFINVENTORY_LQ,
       D.TURNOVERRATIOOFTOTALASSETS as TURNOVERRATIOOFTOTALASSETS_LQ,
       D.DEPRECIATIONOFTOTALCOSTS as DEPRECIATIONOFTOTALCOSTS_LQ,
       D.CASHOFNETPROFIT as CASHOFNETPROFIT_LQ,
       D.CASHOFINTEREST as CASHOFINTEREST_LQ,
       D.ASSETSLIABILITIESRATIO as ASSETSLIABILITIESRATIO_LQ,
       D.TANGIBLEASSETDEBTRATIO as TANGIBLEASSETDEBTRATIO_LQ,
       D.CASHRATIO as CASHRATIO_LQ,
       B1.TOTALASSETS as TOTALASSETS_l2y,
       B1.AVGTOTALASSETS as AVGTOTALASSETS_l2y,
       B1.FIXEDASSETS as FIXEDASSETS_l2y,
       B1.AVGFIXEDASSETS as AVGFIXEDASSETS_l2y,
       B1.GOODWILL as GOODWILL_l2y,
       B1.AVGGOODWILL as AVGGOODWILL_l2y,
       B1.INVENTORY as INVENTORY_l2y,
       B1.MONEYFUNDS as MONEYFUNDS_l2y,
       B1.ACCOUNTSPAYABLE as ACCOUNTSPAYABLE_l2y,
       B1.AVGACCOUNTSPAYABLE as AVGACCOUNTSPAYABLE_l2y,
       B1.AVGINVENTORY as AVGINVENTORY_l2y,
       B1.TOTALLIQUIDASSETS as TOTALLIQUIDASSETS_l2y,
       B1.AVGTOTALLIQUIDASSETS as AVGTOTALLIQUIDASSETS_l2y,
       B1.TOTALLIABILITIES as TOTALLIABILITIES_l2y,
       B1.AVGTOTALLIABILITIES as AVGTOTALLIABILITIES_l2y,
       B1.ACCOUNTSRECEIVABLES as ACCOUNTSRECEIVABLES_l2y,
       B1.AVGACCOUNTSRECEIVABLES as AVGACCOUNTSRECEIVABLES_l2y,
       B1.INTERCOMPANYRECEIVABLES as INTERCOMPANYRECEIVABLES_l2y,
       B1.AVGINTERCOMPANYRECEIVABLES as AVGINTERCOMPANYRECEIVABLES_l2y,
       B1.PREPAYMENTS as PREPAYMENTS_l2y,
       B1.AVGPREPAYMENTS as AVGPREPAYMENTS_l2y,
       B1.TOTALCURRENTLIABILITIES as TOTALCURRENTLIABILITIES_l2y,
       B1.AVGTOTALCURRENTLIABILITIES as AVGTOTALCURRENTLIABILITIES_l2y,
       B1.NETCASHOPERATACTIV as NETCASHOPERATACTIV_l2y,
       B1.CASHOUTINVESTACTIV as CASHOUTINVESTACTIV_l2y,
       B1.operatingRevenue as operatingRevenue_L2Y,
        B1.operatingCosts as operatingCosts_L2Y,
        B1.taxAndSurcharges as taxAndSurcharges_L2Y,
        B1.salesCosts as salesCosts_L2Y,
        B1.managementCosts as managementCosts_L2Y,
        B1.explorationCosts as explorationCosts_L2Y,
        B1.financialCosts as financialCosts_L2Y,
        B1.operatingProfit as operatingProfit_L2Y,
        B1.totalProfit as totalProfit_L2Y,
        B1.incomeTax as incomeTax_L2Y,
       B1.NETPROFIT as NETPROFIT_l2y,
       B1.NETPROFIT_TTM as NETPROFIT_TTM_l2y,
       B1.NETPROAFTEXTRGAINLOSS as NETPROAFTEXTRGAINLOSS_l2y,
       B1.NETPROAFTEXTRGAINLOSS_TTM as NETPROAFTEXTRGAINLOSS_TTM_l2y,
       B1.ROA as ROA_l2y,
       B1.ROA_TTM as ROA_TTM_l2y,
       B1.ROE as ROE_l2y,
       B1.ROE_TTM as ROE_TTM_l2y,
       B1.GROSSMARGIN as GROSSMARGIN_l2y,
       B1.NETROE as NETROE_l2y,
       B1.NETROE_TTM as NETROE_TTM_l2y,
       B1.NETPROFITMARGINONSALES as NETPROFITMARGINONSALES_l2y,
       B1.INCOMETAXRATIO as INCOMETAXRATIO_l2y,
       B1.REINVESTEDINCOMERATIO as REINVESTEDINCOMERATIO_l2y,
       B1.DEPRECIATIONRATIO as DEPRECIATIONRATIO_l2y,
       B1.OPERATINGCASHRATIO as OPERATINGCASHRATIO_l2y,
       B1.AVGFIEXDOFASSETS as AVGFIEXDOFASSETS_l2y,
       B1.FIEXDOFASSETS as FIEXDOFASSETS_l2y,
       B1.ACIDTESTRATIO as ACIDTESTRATIO_l2y,
       B1.TURNOVERRATIOOFRECEIVABLE as TURNOVERRATIOOFRECEIVABLE_l2y,
       B1.TURNOVERRATIOOFINVENTORY as TURNOVERRATIOOFINVENTORY_l2y,
       B1.TURNOVERRATIOOFTOTALASSETS as TURNOVERRATIOOFTOTALASSETS_l2y,
       B1.DEPRECIATIONOFTOTALCOSTS as DEPRECIATIONOFTOTALCOSTS_l2y,
       B1.CASHOFNETPROFIT as CASHOFNETPROFIT_l2y,
       B1.CASHOFINTEREST as CASHOFINTEREST_l2y,
       B1.ASSETSLIABILITIESRATIO as ASSETSLIABILITIESRATIO_l2y,
       B1.TANGIBLEASSETDEBTRATIO as TANGIBLEASSETDEBTRATIO_l2y,
       B1.CASHRATIO as CASHRATIO_l2y,
       B2.TOTALASSETS as TOTALASSETS_L3Y,
       B2.AVGTOTALASSETS as AVGTOTALASSETS_L3Y,
       B2.FIXEDASSETS as FIXEDASSETS_L3Y,
       B2.AVGFIXEDASSETS as AVGFIXEDASSETS_L3Y,
       B2.GOODWILL as GOODWILL_L3Y,
       B2.AVGGOODWILL as AVGGOODWILL_L3Y,
       B2.INVENTORY as INVENTORY_L3Y,
       B2.MONEYFUNDS as MONEYFUNDS_L3Y,
       B2.ACCOUNTSPAYABLE as ACCOUNTSPAYABLE_L3Y,
       B2.AVGACCOUNTSPAYABLE as AVGACCOUNTSPAYABLE_L3Y,
       B2.AVGINVENTORY as AVGINVENTORY_L3Y,
       B2.TOTALLIQUIDASSETS as TOTALLIQUIDASSETS_L3Y,
       B2.AVGTOTALLIQUIDASSETS as AVGTOTALLIQUIDASSETS_L3Y,
       B2.TOTALLIABILITIES as TOTALLIABILITIES_L3Y,
       B2.AVGTOTALLIABILITIES as AVGTOTALLIABILITIES_L3Y,
       B2.ACCOUNTSRECEIVABLES as ACCOUNTSRECEIVABLES_L3Y,
       B2.AVGACCOUNTSRECEIVABLES as AVGACCOUNTSRECEIVABLES_L3Y,
       B2.INTERCOMPANYRECEIVABLES as INTERCOMPANYRECEIVABLES_L3Y,
       B2.AVGINTERCOMPANYRECEIVABLES as AVGINTERCOMPANYRECEIVABLES_L3Y,
       B2.PREPAYMENTS as PREPAYMENTS_L3Y,
       B2.AVGPREPAYMENTS as AVGPREPAYMENTS_L3Y,
       B2.TOTALCURRENTLIABILITIES as TOTALCURRENTLIABILITIES_L3Y,
       B2.AVGTOTALCURRENTLIABILITIES as AVGTOTALCURRENTLIABILITIES_L3Y,
       B2.NETCASHOPERATACTIV as NETCASHOPERATACTIV_L3Y,
       B2.CASHOUTINVESTACTIV as CASHOUTINVESTACTIV_L3Y,
        B2.operatingRevenue as operatingRevenue_L3Y,
        B2.operatingCosts as operatingCosts_L3Y,
        B2.taxAndSurcharges as taxAndSurcharges_L3Y,
        B2.salesCosts as salesCosts_L3Y,
        B2.managementCosts as managementCosts_L3Y,
        B2.explorationCosts as explorationCosts_L3Y,
        B2.financialCosts as financialCosts_L3Y,
        B2.operatingProfit as operatingProfit_L3Y,
        B2.totalProfit as totalProfit_L3Y,
        B2.incomeTax as incomeTax_L3Y,
       B2.NETPROFIT as NETPROFIT_L3Y,
       B2.NETPROFIT_TTM as NETPROFIT_TTM_L3Y,
       B2.NETPROAFTEXTRGAINLOSS as NETPROAFTEXTRGAINLOSS_L3Y,
       B2.NETPROAFTEXTRGAINLOSS_TTM as NETPROAFTEXTRGAINLOSS_TTM_L3Y,
       B2.ROA as ROA_L3Y,
       B2.ROA_TTM as ROA_TTM_L3Y,
       B2.ROE as ROE_L3Y,
       B2.ROE_TTM as ROE_TTM_L3Y,
       B2.GROSSMARGIN as GROSSMARGIN_L3Y,
       B2.NETROE as NETROE_L3Y,
       B2.NETROE_TTM as NETROE_TTM_L3Y,
       B2.NETPROFITMARGINONSALES as NETPROFITMARGINONSALES_L3Y,
       B2.INCOMETAXRATIO as INCOMETAXRATIO_L3Y,
       B2.REINVESTEDINCOMERATIO as REINVESTEDINCOMERATIO_L3Y,
       B2.DEPRECIATIONRATIO as DEPRECIATIONRATIO_L3Y,
       B2.OPERATINGCASHRATIO as OPERATINGCASHRATIO_L3Y,
       B2.AVGFIEXDOFASSETS as AVGFIEXDOFASSETS_L3Y,
       B2.FIEXDOFASSETS as FIEXDOFASSETS_L3Y,
       B2.ACIDTESTRATIO as ACIDTESTRATIO_L3Y,
       B2.TURNOVERRATIOOFRECEIVABLE as TURNOVERRATIOOFRECEIVABLE_L3Y,
       B2.TURNOVERRATIOOFINVENTORY as TURNOVERRATIOOFINVENTORY_L3Y,
       B2.TURNOVERRATIOOFTOTALASSETS as TURNOVERRATIOOFTOTALASSETS_L3Y,
       B2.DEPRECIATIONOFTOTALCOSTS as DEPRECIATIONOFTOTALCOSTS_L3Y,
       B2.CASHOFNETPROFIT as CASHOFNETPROFIT_L3Y,
       B2.CASHOFINTEREST as CASHOFINTEREST_L3Y,
       B2.ASSETSLIABILITIESRATIO as ASSETSLIABILITIESRATIO_L3Y,
       B2.TANGIBLEASSETDEBTRATIO as TANGIBLEASSETDEBTRATIO_L3Y,
       B2.CASHRATIO as CASHRATIO_L3Y,
       B3.TOTALASSETS as TOTALASSETS_L4Y,
       B3.AVGTOTALASSETS as AVGTOTALASSETS_L4Y,
       B3.FIXEDASSETS as FIXEDASSETS_L4Y,
       B3.AVGFIXEDASSETS as AVGFIXEDASSETS_L4Y,
       B3.GOODWILL as GOODWILL_L4Y,
       B3.AVGGOODWILL as AVGGOODWILL_L4Y,
       B3.INVENTORY as INVENTORY_L4Y,
       B3.MONEYFUNDS as MONEYFUNDS_L4Y,
       B3.ACCOUNTSPAYABLE as ACCOUNTSPAYABLE_L4Y,
       B3.AVGACCOUNTSPAYABLE as AVGACCOUNTSPAYABLE_L4Y,
       B3.AVGINVENTORY as AVGINVENTORY_L4Y,
       B3.TOTALLIQUIDASSETS as TOTALLIQUIDASSETS_L4Y,
       B3.AVGTOTALLIQUIDASSETS as AVGTOTALLIQUIDASSETS_L4Y,
       B3.TOTALLIABILITIES as TOTALLIABILITIES_L4Y,
       B3.AVGTOTALLIABILITIES as AVGTOTALLIABILITIES_L4Y,
       B3.ACCOUNTSRECEIVABLES as ACCOUNTSRECEIVABLES_L4Y,
       B3.AVGACCOUNTSRECEIVABLES as AVGACCOUNTSRECEIVABLES_L4Y,
       B3.INTERCOMPANYRECEIVABLES as INTERCOMPANYRECEIVABLES_L4Y,
       B3.AVGINTERCOMPANYRECEIVABLES as AVGINTERCOMPANYRECEIVABLES_L4Y,
       B3.PREPAYMENTS as PREPAYMENTS_L4Y,
       B3.AVGPREPAYMENTS as AVGPREPAYMENTS_L4Y,
       B3.TOTALCURRENTLIABILITIES as TOTALCURRENTLIABILITIES_L4Y,
       B3.AVGTOTALCURRENTLIABILITIES as AVGTOTALCURRENTLIABILITIES_L4Y,
       B3.NETCASHOPERATACTIV as NETCASHOPERATACTIV_L4Y,
       B3.CASHOUTINVESTACTIV as CASHOUTINVESTACTIV_L4Y,
       B3.operatingRevenue as operatingRevenue_L4Y,
        B3.operatingCosts as operatingCosts_L4Y,
        B3.taxAndSurcharges as taxAndSurcharges_L4Y,
        B3.salesCosts as salesCosts_L4Y,
        B3.managementCosts as managementCosts_L4Y,
        B3.explorationCosts as explorationCosts_L4Y,
        B3.financialCosts as financialCosts_L4Y,
        B3.operatingProfit as operatingProfit_L4Y,
        B3.totalProfit as totalProfit_L4Y,
        B3.incomeTax as incomeTax_L4Y,
       B3.NETPROFIT as NETPROFIT_L4Y,
       B3.NETPROFIT_TTM as NETPROFIT_TTM_L4Y,
       B3.NETPROAFTEXTRGAINLOSS as NETPROAFTEXTRGAINLOSS_L4Y,
       B3.NETPROAFTEXTRGAINLOSS_TTM as NETPROAFTEXTRGAINLOSS_TTM_L4Y,
       B3.ROA as ROA_L4Y,
       B3.ROA_TTM as ROA_TTM_L4Y,
       B3.ROE as ROE_L4Y,
       B3.ROE_TTM as ROE_TTM_L4Y,
       B3.GROSSMARGIN as GROSSMARGIN_L4Y,
       B3.NETROE as NETROE_L4Y,
       B3.NETROE_TTM as NETROE_TTM_L4Y,
       B3.NETPROFITMARGINONSALES as NETPROFITMARGINONSALES_L4Y,
       B3.INCOMETAXRATIO as INCOMETAXRATIO_L4Y,
       B3.REINVESTEDINCOMERATIO as REINVESTEDINCOMERATIO_L4Y,
       B3.DEPRECIATIONRATIO as DEPRECIATIONRATIO_L4Y,
       B3.OPERATINGCASHRATIO as OPERATINGCASHRATIO_L4Y,
       B3.AVGFIEXDOFASSETS as AVGFIEXDOFASSETS_L4Y,
       B3.FIEXDOFASSETS as FIEXDOFASSETS_L4Y,
       B3.ACIDTESTRATIO as ACIDTESTRATIO_L4Y,
       B3.TURNOVERRATIOOFRECEIVABLE as TURNOVERRATIOOFRECEIVABLE_L4Y,
       B3.TURNOVERRATIOOFINVENTORY as TURNOVERRATIOOFINVENTORY_L4Y,
       B3.TURNOVERRATIOOFTOTALASSETS as TURNOVERRATIOOFTOTALASSETS_L4Y,
       B3.DEPRECIATIONOFTOTALCOSTS as DEPRECIATIONOFTOTALCOSTS_L4Y,
       B3.CASHOFNETPROFIT as CASHOFNETPROFIT_L4Y,
       B3.CASHOFINTEREST as CASHOFINTEREST_L4Y,
       B3.ASSETSLIABILITIESRATIO as ASSETSLIABILITIESRATIO_L4Y,
       B3.TANGIBLEASSETDEBTRATIO as TANGIBLEASSETDEBTRATIO_L4Y,
       B3.CASHRATIO as CASHRATIO_L4Y,
       B4.TOTALASSETS as TOTALASSETS_L5Y,
       B4.AVGTOTALASSETS as AVGTOTALASSETS_L5Y,
       B4.FIXEDASSETS as FIXEDASSETS_L5Y,
       B4.AVGFIXEDASSETS as AVGFIXEDASSETS_L5Y,
       B4.GOODWILL as GOODWILL_L5Y,
       B4.AVGGOODWILL as AVGGOODWILL_L5Y,
       B4.INVENTORY as INVENTORY_L5Y,
       B4.MONEYFUNDS as MONEYFUNDS_L5Y,
       B4.ACCOUNTSPAYABLE as ACCOUNTSPAYABLE_L5Y,
       B4.AVGACCOUNTSPAYABLE as AVGACCOUNTSPAYABLE_L5Y,
       B4.AVGINVENTORY as AVGINVENTORY_L5Y,
       B4.TOTALLIQUIDASSETS as TOTALLIQUIDASSETS_L5Y,
       B4.AVGTOTALLIQUIDASSETS as AVGTOTALLIQUIDASSETS_L5Y,
       B4.TOTALLIABILITIES as TOTALLIABILITIES_L5Y,
       B4.AVGTOTALLIABILITIES as AVGTOTALLIABILITIES_L5Y,
       B4.ACCOUNTSRECEIVABLES as ACCOUNTSRECEIVABLES_L5Y,
       B4.AVGACCOUNTSRECEIVABLES as AVGACCOUNTSRECEIVABLES_L5Y,
       B4.INTERCOMPANYRECEIVABLES as INTERCOMPANYRECEIVABLES_L5Y,
       B4.AVGINTERCOMPANYRECEIVABLES as AVGINTERCOMPANYRECEIVABLES_L5Y,
       B4.PREPAYMENTS as PREPAYMENTS_L5Y,
       B4.AVGPREPAYMENTS as AVGPREPAYMENTS_L5Y,
       B4.TOTALCURRENTLIABILITIES as TOTALCURRENTLIABILITIES_L5Y,
       B4.AVGTOTALCURRENTLIABILITIES as AVGTOTALCURRENTLIABILITIES_L5Y,
       B4.NETCASHOPERATACTIV as NETCASHOPERATACTIV_L5Y,
       B4.CASHOUTINVESTACTIV as CASHOUTINVESTACTIV_L5Y,
       B4.operatingRevenue as operatingRevenue_L5Y,
        B4.operatingCosts as operatingCosts_L5Y,
        B4.taxAndSurcharges as taxAndSurcharges_L5Y,
        B4.salesCosts as salesCosts_L5Y,
        B4.managementCosts as managementCosts_L5Y,
        B4.explorationCosts as explorationCosts_L5Y,
        B4.financialCosts as financialCosts_L5Y,
        B4.operatingProfit as operatingProfit_L5Y,
        B4.totalProfit as totalProfit_L5Y,
        B4.incomeTax as incomeTax_L5Y,
       B4.NETPROFIT as NETPROFIT_L5Y,
       B4.NETPROFIT_TTM as NETPROFIT_TTM_L5Y,
       B4.NETPROAFTEXTRGAINLOSS as NETPROAFTEXTRGAINLOSS_L5Y,
       B4.NETPROAFTEXTRGAINLOSS_TTM as NETPROAFTEXTRGAINLOSS_TTM_L5Y,
       B4.ROA as ROA_L5Y,
       B4.ROA_TTM as ROA_TTM_L5Y,
       B4.ROE as ROE_L5Y,
       B4.ROE_TTM as ROE_TTM_L5Y,
       B4.GROSSMARGIN as GROSSMARGIN_L5Y,
       B4.NETROE as NETROE_L5Y,
       B4.NETROE_TTM as NETROE_TTM_L5Y,
       B4.NETPROFITMARGINONSALES as NETPROFITMARGINONSALES_L5Y,
       B4.INCOMETAXRATIO as INCOMETAXRATIO_L5Y,
       B4.REINVESTEDINCOMERATIO as REINVESTEDINCOMERATIO_L5Y,
       B4.DEPRECIATIONRATIO as DEPRECIATIONRATIO_L5Y,
       B4.OPERATINGCASHRATIO as OPERATINGCASHRATIO_L5Y,
       B4.AVGFIEXDOFASSETS as AVGFIEXDOFASSETS_L5Y,
       B4.FIEXDOFASSETS as FIEXDOFASSETS_L5Y,
       B4.ACIDTESTRATIO as ACIDTESTRATIO_L5Y,
       B4.TURNOVERRATIOOFRECEIVABLE as TURNOVERRATIOOFRECEIVABLE_L5Y,
       B4.TURNOVERRATIOOFINVENTORY as TURNOVERRATIOOFINVENTORY_L5Y,
       B4.TURNOVERRATIOOFTOTALASSETS as TURNOVERRATIOOFTOTALASSETS_L5Y,
       B4.DEPRECIATIONOFTOTALCOSTS as DEPRECIATIONOFTOTALCOSTS_L5Y,
       B4.CASHOFNETPROFIT as CASHOFNETPROFIT_L5Y,
       B4.CASHOFINTEREST as CASHOFINTEREST_L5Y,
       B4.ASSETSLIABILITIESRATIO as ASSETSLIABILITIESRATIO_L5Y,
       B4.TANGIBLEASSETDEBTRATIO as TANGIBLEASSETDEBTRATIO_L5Y,
       B4.CASHRATIO as CASHRATIO_L5Y
  FROM res A
  LEFT JOIN res B
    ON B.REPORT_DATE = ADD_MONTHS(A.REPORT_DATE, -12)
   AND A.CODE = B.CODE
  LEFT JOIN res D
    ON D.REPORT_DATE = ADD_MONTHS(A.REPORT_DATE, -3)
   AND A.CODE = D.CODE
  LEFT JOIN res B1
    ON B1.REPORT_DATE = ADD_MONTHS(A.REPORT_DATE, -24)
   AND A.CODE = B1.CODE
  LEFT JOIN res B2
    ON B2.REPORT_DATE = ADD_MONTHS(A.REPORT_DATE, -36)
   AND A.CODE = B2.CODE
  LEFT JOIN res B3
    ON B3.REPORT_DATE = ADD_MONTHS(A.REPORT_DATE, -48)
   AND A.CODE = B3.CODE
  LEFT JOIN res B4
    ON B4.REPORT_DATE = ADD_MONTHS(A.REPORT_DATE, -60)
   AND A.CODE = B4.CODE
        '''
    conn = cx_Oracle.connect(ORACLE_PATH2)
    cursor = conn.cursor()
    try:
        cursor.execute('''drop table stock_financial_TTM''')
    except:
        pass
    cursor.execute(sql1)
    conn.commit()
    try:
        cursor.execute('''drop table stock_financial_analysis''')
    except:
        pass
    cursor.execute(sql2)
    conn.commit()
    QA_util_log_info("financial TTM report has been stored")
    cursor.close()
    conn.commit()
    conn.close()

def QA_util_etl_financial_TTM(ui_log= None):
    QA_util_log_info(
        '##JOB01 Now Etl Stock Financial TTM ==== {}'.format(QA_util_today_str()), ui_log)

    sql = '''select CODE,
                INDUSTRY,
                NAME,
                AREA,
                TO_CHAR(REPORT_DATE, 'YYYY-MM-DD') AS REPORT_DATE,
                TO_CHAR(LASTYEAR, 'YYYY-MM-DD') AS LASTYEAR,
                TO_CHAR(LAG1, 'YYYY-MM-DD') AS LAG1,
                TO_CHAR(LAST2YEAR, 'YYYY-MM-DD') AS LAST2YEAR,
                TO_CHAR(LAST3YEAR, 'YYYY-MM-DD') AS LAST3YEAR,
                TO_CHAR(LAST4YEAR, 'YYYY-MM-DD') AS LAST4YEAR,
                TO_CHAR(LAST5YEAR, 'YYYY-MM-DD') AS LAST5YEAR,
                TO_CHAR(SEND_DATE, 'YYYY-MM-DD') AS SEND_DATE,
                TO_CHAR(END_DATE, 'YYYY-MM-DD') AS END_DATE,
                TOTALASSETS,
                AVGTOTALASSETS,
                FIXEDASSETS,
                AVGFIXEDASSETS,
                GOODWILL,
                AVGGOODWILL,
                INVENTORY,
                MONEYFUNDS,
                ACCOUNTSPAYABLE,
                AVGACCOUNTSPAYABLE,
                AVGINVENTORY,
                TOTALLIQUIDASSETS,
                AVGTOTALLIQUIDASSETS,
                TOTALLIABILITIES,
                AVGTOTALLIABILITIES,
                ACCOUNTSRECEIVABLES,
                AVGACCOUNTSRECEIVABLES,
                INTERCOMPANYRECEIVABLES,
                AVGINTERCOMPANYRECEIVABLES,
                PREPAYMENTS,
                AVGPREPAYMENTS,
                TOTALCURRENTLIABILITIES,
                AVGTOTALCURRENTLIABILITIES,
                NETCASHOPERATACTIV,
                CASHOUTINVESTACTIV,
                NETPROFIT,
                OPERATINGREVENUE_TTM,
                OPERATINGCOSTS_TTM,
                TAXANDSURCHARGES_TTM,
                SALESCOSTS_TTM,
                MANAGEMENTCOSTS_TTM,
                EXPLORATIONCOSTS_TTM,
                FINANCIALCOSTS_TTM,
                ASSESTSDEVALUATION_TTM,
                OPERATINGPROFIT_TTM,
                TOTALPROFIT_TTM,
                INCOMETAX_TTM,
                NETPROFIT_TTM,
                NETPROAFTEXTRGAINLOSS_TTM,
                INTEREST_TTM,
                DEPRECFORFIXEDASSETS_TTM,
                NETCASHOPERATACTIV_TTM,
                CASHOUTINVESTACTIV_TTM,
                ROE,
                GROSSMARGIN,
                ROA,
                NETPROFITMARGINONSALES_TTM,
                INCOMETAXRATIO,
                REINVESTEDINCOMERATIO,
                DEPRECIATIONRATIO,
                OPERATINGCASHRATIO_TTM,
                AVGFIEXDOFASSETS,
                FIEXDOFASSETS,
                ACIDTESTRATIO,
                TURNOVERRATIOOFRECEIVABLE,
                TURNOVERRATIOOFINVENTORY,
                TURNOVERRATIOOFTOTALASSETS,
                DEPRECIATIONOFTOTALCOSTS,
                CASHOFNETPROFIT,
                CASHOFNETPROFIT_TTM,
                CASHOFINTEREST,
                ASSETSLIABILITIESRATIO,
                TANGIBLEASSETDEBTRATIO,
                CASHRATIO,
                TOTALASSETS_LY,
                AVGTOTALASSETS_LY,
                FIXEDASSETS_LY,
                AVGFIXEDASSETS_LY,
                GOODWILL_LY,
                AVGGOODWILL_LY,
                INVENTORY_LY,
                MONEYFUNDS_LY,
                ACCOUNTSPAYABLE_LY,
                AVGACCOUNTSPAYABLE_LY,
                AVGINVENTORY_LY,
                TOTALLIQUIDASSETS_LY,
                AVGTOTALLIQUIDASSETS_LY,
                TOTALLIABILITIES_LY,
                AVGTOTALLIABILITIES_LY,
                ACCOUNTSRECEIVABLES_LY,
                AVGACCOUNTSRECEIVABLES_LY,
                INTERCOMPANYRECEIVABLES_LY,
                AVGINTERCOMPANYRECEIVABLES_LY,
                PREPAYMENTS_LY,
                AVGPREPAYMENTS_LY,
                TOTALCURRENTLIABILITIES_LY,
                AVGTOTALCURRENTLIABILITIES_LY,
                NETCASHOPERATACTIV_LY,
                CASHOUTINVESTACTIV_LY,
                NETPROFIT_LY,
                OPERATINGREVENUE_TTM_LY,
                OPERATINGCOSTS_TTM_LY,
                TAXANDSURCHARGES_TTM_LY,
                SALESCOSTS_TTM_LY,
                MANAGEMENTCOSTS_TTM_LY,
                EXPLORATIONCOSTS_TTM_LY,
                FINANCIALCOSTS_TTM_LY,
                ASSESTSDEVALUATION_TTM_LY,
                OPERATINGPROFIT_TTM_LY,
                TOTALPROFIT_TTM_LY,
                INCOMETAX_TTM_LY,
                NETPROFIT_TTM_LY,
                NETPROAFTEXTRGAINLOSS_TTM_LY,
                INTEREST_TTM_LY,
                DEPRECFORFIXEDASSETS_TTM_LY,
                NETCASHOPERATACTIV_TTM_LY,
                CASHOUTINVESTACTIV_TTM_LY,
                ROE_LY,
                GROSSMARGIN_LY,
                ROA_LY,
                NETPROFITMARGINONSALES_TTM_LY,
                INCOMETAXRATIO_LY,
                REINVESTEDINCOMERATIO_LY,
                DEPRECIATIONRATIO_LY,
                OPERATINGCASHRATIO_TTM_LY,
                AVGFIEXDOFASSETS_LY,
                FIEXDOFASSETS_LY,
                ACIDTESTRATIO_LY,
                TURNOVERRATIOOFRECEIVABLE_LY,
                TURNOVERRATIOOFINVENTORY_LY,
                TURNOVERRATIOOFTOTALASSETS_LY,
                DEPRECIATIONOFTOTALCOSTS_LY,
                CASHOFNETPROFIT_LY,
                CASHOFNETPROFIT_TTM_LY,
                CASHOFINTEREST_LY,
                ASSETSLIABILITIESRATIO_LY,
                TANGIBLEASSETDEBTRATIO_LY,
                CASHRATIO_LY,
                TOTALASSETS_L2Y,
                AVGTOTALASSETS_L2Y,
                FIXEDASSETS_L2Y,
                AVGFIXEDASSETS_L2Y,
                GOODWILL_L2Y,
                AVGGOODWILL_L2Y,
                INVENTORY_L2Y,
                MONEYFUNDS_L2Y,
                ACCOUNTSPAYABLE_L2Y,
                AVGACCOUNTSPAYABLE_L2Y,
                AVGINVENTORY_L2Y,
                TOTALLIQUIDASSETS_L2Y,
                AVGTOTALLIQUIDASSETS_L2Y,
                TOTALLIABILITIES_L2Y,
                AVGTOTALLIABILITIES_L2Y,
                ACCOUNTSRECEIVABLES_L2Y,
                AVGACCOUNTSRECEIVABLES_L2Y,
                INTERCOMPANYRECEIVABLES_L2Y,
                AVGINTERCOMPANYRECEIVABLES_L2Y,
                PREPAYMENTS_L2Y,
                AVGPREPAYMENTS_L2Y,
                TOTALCURRENTLIABILITIES_L2Y,
                AVGTOTALCURRENTLIABILITIES_L2Y,
                NETCASHOPERATACTIV_L2Y,
                CASHOUTINVESTACTIV_L2Y,
                NETPROFIT_L2Y,
                OPERATINGREVENUE_TTM_L2Y,
                OPERATINGCOSTS_TTM_L2Y,
                TAXANDSURCHARGES_TTM_L2Y,
                SALESCOSTS_TTM_L2Y,
                MANAGEMENTCOSTS_TTM_L2Y,
                EXPLORATIONCOSTS_TTM_L2Y,
                FINANCIALCOSTS_TTM_L2Y,
                ASSESTSDEVALUATION_TTM_L2Y,
                OPERATINGPROFIT_TTM_L2Y,
                TOTALPROFIT_TTM_L2Y,
                INCOMETAX_TTM_L2Y,
                NETPROFIT_TTM_L2Y,
                NETPROAFTEXTRGAINLOSS_TTM_L2Y,
                INTEREST_TTM_L2Y,
                DEPRECFORFIXEDASSETS_TTM_L2Y,
                NETCASHOPERATACTIV_TTM_L2Y,
                CASHOUTINVESTACTIV_TTM_L2Y,
                ROE_L2Y,
                GROSSMARGIN_L2Y,
                ROA_L2Y,
                NETPROFITMARGINONSALES_TTM_L2Y,
                INCOMETAXRATIO_L2Y,
                REINVESTEDINCOMERATIO_L2Y,
                DEPRECIATIONRATIO_L2Y,
                OPERATINGCASHRATIO_TTM_L2Y,
                AVGFIEXDOFASSETS_L2Y,
                FIEXDOFASSETS_L2Y,
                ACIDTESTRATIO_L2Y,
                TURNOVERRATIOOFRECEIVABLE_L2Y,
                TURNOVERRATIOOFINVENTORY_L2Y,
                TURNOVERRATIOOFTOTALASSETS_L2Y,
                DEPRECIATIONOFTOTALCOSTS_L2Y,
                CASHOFNETPROFIT_L2Y,
                CASHOFNETPROFIT_TTM_L2Y,
                CASHOFINTEREST_L2Y,
                ASSETSLIABILITIESRATIO_L2Y,
                TANGIBLEASSETDEBTRATIO_L2Y,
                CASHRATIO_L2Y,
                TOTALASSETS_L3Y,
                AVGTOTALASSETS_L3Y,
                FIXEDASSETS_L3Y,
                AVGFIXEDASSETS_L3Y,
                GOODWILL_L3Y,
                AVGGOODWILL_L3Y,
                INVENTORY_L3Y,
                MONEYFUNDS_L3Y,
                ACCOUNTSPAYABLE_L3Y,
                AVGACCOUNTSPAYABLE_L3Y,
                AVGINVENTORY_L3Y,
                TOTALLIQUIDASSETS_L3Y,
                AVGTOTALLIQUIDASSETS_L3Y,
                TOTALLIABILITIES_L3Y,
                AVGTOTALLIABILITIES_L3Y,
                ACCOUNTSRECEIVABLES_L3Y,
                AVGACCOUNTSRECEIVABLES_L3Y,
                INTERCOMPANYRECEIVABLES_L3Y,
                AVGINTERCOMPANYRECEIVABLES_L3Y,
                PREPAYMENTS_L3Y,
                AVGPREPAYMENTS_L3Y,
                TOTALCURRENTLIABILITIES_L3Y,
                AVGTOTALCURRENTLIABILITIES_L3Y,
                NETCASHOPERATACTIV_L3Y,
                CASHOUTINVESTACTIV_L3Y,
                NETPROFIT_L3Y,
                OPERATINGREVENUE_TTM_L3Y,
                OPERATINGCOSTS_TTM_L3Y,
                TAXANDSURCHARGES_TTM_L3Y,
                SALESCOSTS_TTM_L3Y,
                MANAGEMENTCOSTS_TTM_L3Y,
                EXPLORATIONCOSTS_TTM_L3Y,
                FINANCIALCOSTS_TTM_L3Y,
                ASSESTSDEVALUATION_TTM_L3Y,
                OPERATINGPROFIT_TTM_L3Y,
                TOTALPROFIT_TTM_L3Y,
                INCOMETAX_TTM_L3Y,
                NETPROFIT_TTM_L3Y,
                NETPROAFTEXTRGAINLOSS_TTM_L3Y,
                INTEREST_TTM_L3Y,
                DEPRECFORFIXEDASSETS_TTM_L3Y,
                NETCASHOPERATACTIV_TTM_L3Y,
                CASHOUTINVESTACTIV_TTM_L3Y,
                ROE_L3Y,
                GROSSMARGIN_L3Y,
                ROA_L3Y,
                NETPROFITMARGINONSALES_TTM_L3Y,
                INCOMETAXRATIO_L3Y,
                REINVESTEDINCOMERATIO_L3Y,
                DEPRECIATIONRATIO_L3Y,
                OPERATINGCASHRATIO_TTM_L3Y,
                AVGFIEXDOFASSETS_L3Y,
                FIEXDOFASSETS_L3Y,
                ACIDTESTRATIO_L3Y,
                TURNOVERRATIOOFRECEIVABLE_L3Y,
                TURNOVERRATIOOFINVENTORY_L3Y,
                TURNOVERRATIOOFTOTALASSETS_L3Y,
                DEPRECIATIONOFTOTALCOSTS_L3Y,
                CASHOFNETPROFIT_L3Y,
                CASHOFNETPROFIT_TTM_L3Y,
                CASHOFINTEREST_L3Y,
                ASSETSLIABILITIESRATIO_L3Y,
                TANGIBLEASSETDEBTRATIO_L3Y,
                CASHRATIO_L3Y,
                TOTALASSETS_L4Y,
                AVGTOTALASSETS_L4Y,
                FIXEDASSETS_L4Y,
                AVGFIXEDASSETS_L4Y,
                GOODWILL_L4Y,
                AVGGOODWILL_L4Y,
                INVENTORY_L4Y,
                MONEYFUNDS_L4Y,
                ACCOUNTSPAYABLE_L4Y,
                AVGACCOUNTSPAYABLE_L4Y,
                AVGINVENTORY_L4Y,
                TOTALLIQUIDASSETS_L4Y,
                AVGTOTALLIQUIDASSETS_L4Y,
                TOTALLIABILITIES_L4Y,
                AVGTOTALLIABILITIES_L4Y,
                ACCOUNTSRECEIVABLES_L4Y,
                AVGACCOUNTSRECEIVABLES_L4Y,
                INTERCOMPANYRECEIVABLES_L4Y,
                AVGINTERCOMPANYRECEIVABLES_L4Y,
                PREPAYMENTS_L4Y,
                AVGPREPAYMENTS_L4Y,
                TOTALCURRENTLIABILITIES_L4Y,
                AVGTOTALCURRENTLIABILITIES_L4Y,
                NETCASHOPERATACTIV_L4Y,
                CASHOUTINVESTACTIV_L4Y,
                NETPROFIT_L4Y,
                OPERATINGREVENUE_TTM_L4Y,
                OPERATINGCOSTS_TTM_L4Y,
                TAXANDSURCHARGES_TTM_L4Y,
                SALESCOSTS_TTM_L4Y,
                MANAGEMENTCOSTS_TTM_L4Y,
                EXPLORATIONCOSTS_TTM_L4Y,
                FINANCIALCOSTS_TTM_L4Y,
                ASSESTSDEVALUATION_TTM_L4Y,
                OPERATINGPROFIT_TTM_L4Y,
                TOTALPROFIT_TTM_L4Y,
                INCOMETAX_TTM_L4Y,
                NETPROFIT_TTM_L4Y,
                NETPROAFTEXTRGAINLOSS_TTM_L4Y,
                INTEREST_TTM_L4Y,
                DEPRECFORFIXEDASSETS_TTM_L4Y,
                NETCASHOPERATACTIV_TTM_L4Y,
                CASHOUTINVESTACTIV_TTM_L4Y,
                ROE_L4Y,
                GROSSMARGIN_L4Y,
                ROA_L4Y,
                NETPROFITMARGINONSALES_TTM_L4Y,
                INCOMETAXRATIO_L4Y,
                REINVESTEDINCOMERATIO_L4Y,
                DEPRECIATIONRATIO_L4Y,
                OPERATINGCASHRATIO_TTM_L4Y,
                AVGFIEXDOFASSETS_L4Y,
                FIEXDOFASSETS_L4Y,
                ACIDTESTRATIO_L4Y,
                TURNOVERRATIOOFRECEIVABLE_L4Y,
                TURNOVERRATIOOFINVENTORY_L4Y,
                TURNOVERRATIOOFTOTALASSETS_L4Y,
                DEPRECIATIONOFTOTALCOSTS_L4Y,
                CASHOFNETPROFIT_L4Y,
                CASHOFNETPROFIT_TTM_L4Y,
                CASHOFINTEREST_L4Y,
                ASSETSLIABILITIESRATIO_L4Y,
                TANGIBLEASSETDEBTRATIO_L4Y,
                CASHRATIO_L4Y,
                TOTALASSETS_L5Y,
                AVGTOTALASSETS_L5Y,
                FIXEDASSETS_L5Y,
                AVGFIXEDASSETS_L5Y,
                GOODWILL_L5Y,
                AVGGOODWILL_L5Y,
                INVENTORY_L5Y,
                MONEYFUNDS_L5Y,
                ACCOUNTSPAYABLE_L5Y,
                AVGACCOUNTSPAYABLE_L5Y,
                AVGINVENTORY_L5Y,
                TOTALLIQUIDASSETS_L5Y,
                AVGTOTALLIQUIDASSETS_L5Y,
                TOTALLIABILITIES_L5Y,
                AVGTOTALLIABILITIES_L5Y,
                ACCOUNTSRECEIVABLES_L5Y,
                AVGACCOUNTSRECEIVABLES_L5Y,
                INTERCOMPANYRECEIVABLES_L5Y,
                AVGINTERCOMPANYRECEIVABLES_L5Y,
                PREPAYMENTS_L5Y,
                AVGPREPAYMENTS_L5Y,
                TOTALCURRENTLIABILITIES_L5Y,
                AVGTOTALCURRENTLIABILITIES_L5Y,
                NETCASHOPERATACTIV_L5Y,
                CASHOUTINVESTACTIV_L5Y,
                NETPROFIT_L5Y,
                OPERATINGREVENUE_TTM_L5Y,
                OPERATINGCOSTS_TTM_L5Y,
                TAXANDSURCHARGES_TTM_L5Y,
                SALESCOSTS_TTM_L5Y,
                MANAGEMENTCOSTS_TTM_L5Y,
                EXPLORATIONCOSTS_TTM_L5Y,
                FINANCIALCOSTS_TTM_L5Y,
                ASSESTSDEVALUATION_TTM_L5Y,
                OPERATINGPROFIT_TTM_L5Y,
                TOTALPROFIT_TTM_L5Y,
                INCOMETAX_TTM_L5Y,
                NETPROFIT_TTM_L5Y,
                NETPROAFTEXTRGAINLOSS_TTM_L5Y,
                INTEREST_TTM_L5Y,
                DEPRECFORFIXEDASSETS_TTM_L5Y,
                NETCASHOPERATACTIV_TTM_L5Y,
                CASHOUTINVESTACTIV_TTM_L5Y,
                ROE_L5Y,
                GROSSMARGIN_L5Y,
                ROA_L5Y,
                NETPROFITMARGINONSALES_TTM_L5Y,
                INCOMETAXRATIO_L5Y,
                REINVESTEDINCOMERATIO_L5Y,
                DEPRECIATIONRATIO_L5Y,
                OPERATINGCASHRATIO_TTM_L5Y,
                AVGFIEXDOFASSETS_L5Y,
                FIEXDOFASSETS_L5Y,
                ACIDTESTRATIO_L5Y,
                TURNOVERRATIOOFRECEIVABLE_L5Y,
                TURNOVERRATIOOFINVENTORY_L5Y,
                TURNOVERRATIOOFTOTALASSETS_L5Y,
                DEPRECIATIONOFTOTALCOSTS_L5Y,
                CASHOFNETPROFIT_L5Y,
                CASHOFNETPROFIT_TTM_L5Y,
                CASHOFINTEREST_L5Y,
                ASSETSLIABILITIESRATIO_L5Y,
                TANGIBLEASSETDEBTRATIO_L5Y,
                CASHRATIO_L5Y,
                TOTALASSETS_LQ,
                AVGTOTALASSETS_LQ,
                FIXEDASSETS_LQ,
                AVGFIXEDASSETS_LQ,
                GOODWILL_LQ,
                AVGGOODWILL_LQ,
                INVENTORY_LQ,
                MONEYFUNDS_LQ,
                ACCOUNTSPAYABLE_LQ,
                AVGACCOUNTSPAYABLE_LQ,
                AVGINVENTORY_LQ,
                TOTALLIQUIDASSETS_LQ,
                AVGTOTALLIQUIDASSETS_LQ,
                TOTALLIABILITIES_LQ,
                AVGTOTALLIABILITIES_LQ,
                ACCOUNTSRECEIVABLES_LQ,
                AVGACCOUNTSRECEIVABLES_LQ,
                INTERCOMPANYRECEIVABLES_LQ,
                AVGINTERCOMPANYRECEIVABLES_LQ,
                PREPAYMENTS_LQ,
                AVGPREPAYMENTS_LQ,
                TOTALCURRENTLIABILITIES_LQ,
                AVGTOTALCURRENTLIABILITIES_LQ,
                NETCASHOPERATACTIV_LQ,
                CASHOUTINVESTACTIV_LQ,
                NETPROFIT_LQ,
                OPERATINGREVENUE_TTM_LQ,
                OPERATINGCOSTS_TTM_LQ,
                TAXANDSURCHARGES_TTM_LQ,
                SALESCOSTS_TTM_LQ,
                MANAGEMENTCOSTS_TTM_LQ,
                EXPLORATIONCOSTS_TTM_LQ,
                FINANCIALCOSTS_TTM_LQ,
                ASSESTSDEVALUATION_TTM_LQ,
                OPERATINGPROFIT_TTM_LQ,
                TOTALPROFIT_TTM_LQ,
                INCOMETAX_TTM_LQ,
                NETPROFIT_TTM_LQ,
                NETPROAFTEXTRGAINLOSS_TTM_LQ,
                INTEREST_TTM_LQ,
                DEPRECFORFIXEDASSETS_TTM_LQ,
                NETCASHOPERATACTIV_TTM_LQ,
                CASHOUTINVESTACTIV_TTM_LQ,
                ROE_LQ,
                GROSSMARGIN_LQ,
                ROA_LQ,
                NETPROFITMARGINONSALES_TTM_LQ,
                INCOMETAXRATIO_LQ,
                REINVESTEDINCOMERATIO_LQ,
                DEPRECIATIONRATIO_LQ,
                OPERATINGCASHRATIO_TTM_LQ,
                AVGFIEXDOFASSETS_LQ,
                FIEXDOFASSETS_LQ,
                ACIDTESTRATIO_LQ,
                TURNOVERRATIOOFRECEIVABLE_LQ,
                TURNOVERRATIOOFINVENTORY_LQ,
                TURNOVERRATIOOFTOTALASSETS_LQ,
                DEPRECIATIONOFTOTALCOSTS_LQ,
                CASHOFNETPROFIT_LQ,
                CASHOFNETPROFIT_TTM_LQ,
                CASHOFINTEREST_LQ,
                ASSETSLIABILITIESRATIO_LQ,
                TANGIBLEASSETDEBTRATIO_LQ,
                CASHRATIO_LQ
  from stock_financial_analysis
    '''
    conn = cx_Oracle.connect(ORACLE_PATH2)
    data = pd.read_sql(sql=sql, con=conn)
    data = data.assign(date_stamp=data['REPORT_DATE'].apply(lambda x: QA_util_date_stamp(str(x)[0:10])))
    conn.close()
    return(data)